### ISSUE TITLE
Compilation error on Linux: value of type 'sockaddr' has no member 'sa_len'

### ISSUE THREAD

**Issue by mwermeester** [twostraws/Ignite#826]
Similar to #821, encountering an error when compiling Ignite on Linux with Swift 6.1 installed: 

[7/9] Compiling IgniteCLI BuildCommand.swift
/codebuild/output/src3290797122/src/github.com/mwermeester/Ignite/Sources/IgniteCLI/Process-Execute.swift:34:17: warning: 'launchPath' is deprecated: renamed to 'executableURL'
32 |     ) throws -> (output: String, error: String) {
33 |         let process = Process()
34 |         process.launchPath = "/bin/bash"
   |                 |- warning: 'launchPath' is deprecated: renamed to 'executableURL'
   |                 `- note: use 'executableURL' instead
35 |         process.arguments = ["-c"] + [command]
36 | 

/codebuild/output/src3290797122/src/github.com/mwermeester/Ignite/Sources/IgniteCLI/RunCommand.swift:114:104: error: value of type 'sockaddr' has no member 'sa_len'
112 |                     let interfaceName = String(cString: networkInterface.ifa_name)
113 |                     var hostNameBuffer = [CChar](repeating: 0, count: Int(NI_MAXHOST))
114 |                     getnameinfo(networkInterface.ifa_addr, socklen_t(networkInterface.ifa_addr.pointee.sa_len),
    |                                                                                                        `- error: value of type 'sockaddr' has no member 'sa_len'
115 |                                 &hostNameBuffer, socklen_t(hostNameBuffer.count),
116 |                                 nil, socklen_t(0), NI_NUMERICHOST)
make: *** [build] Error 1

[Container] 2025/05/03 14:07:07.532386 Command did not exit successfully make exit status 2
[Container] 2025/05/03 14:07:07.538770 Phase complete: BUILD State: FAILED
[Container] 2025/05/03 14:07:07.538788 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: make. Reason: exit status 2

**Comment by JPToroDev** [comment]
Thanks for flagging! Fixed with the latest commits?

**Comment by mwermeester** [comment]
Perhaps this can help? 

[Network code not compiling on Ubuntu - “‘sockaddr’ has no member ‘sa_len’”](https://forums.swift.org/t/network-code-not-compiling-on-ubuntu-sockaddr-has-no-member-sa-len/53184)

**Comment by mwermeester** [comment]
Unfortunately not fixed, still getting the error:

```
[7/9] Compiling IgniteCLI BuildCommand.swift
/codebuild/output/src264457623/src/github.com/mwermeester/Ignite/Sources/IgniteCLI/RunCommand.swift:123:104: error: value of type 'sockaddr' has no member 'sa_len'
121 |                     let interfaceName = String(cString: networkInterface.ifa_name)
122 |                     var hostNameBuffer = [CChar](repeating: 0, count: Int(NI_MAXHOST))
123 |                     getnameinfo(networkInterface.ifa_addr, socklen_t(networkInterface.ifa_addr.pointee.sa_len),
    |                                                                                                        `- error: value of type 'sockaddr' has no member 'sa_len'
124 |                                 &hostNameBuffer, socklen_t(hostNameBuffer.count),
125 |                                 nil, socklen_t(0), NI_NUMERICHOST)
make: *** [build] Error 1
```

The warning has disappeared though.

**Comment by JPToroDev** [comment]
How about now?

**Comment by mwermeester** [comment]
Fixed, thanks a lot!

No more compilation errors on Linux.

**Comment by JPToroDev** [comment]
Great! Thanks for the quick replies :D
